import os
from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN
from pptx.enum.shapes import MSO_SHAPE


class PowerPointGenerator:

    def __init__(self):
        self.blue = RGBColor(37, 99, 235)       # #2563EB
        self.dark = RGBColor(17, 24, 39)        # #111827
        self.gray = RGBColor(107, 114, 128)     # #6B7280
        self.light_bg = RGBColor(248, 250, 252) # #F8FAFC
        self.border_gray = RGBColor(209, 213, 219) # #D1D5DB

    def generate(self, company: str, slides: list, output_path: str = None) -> str:
        if not output_path:
            output_path = os.path.join(
                "app", "output", "presentations", f"{company}_Placement_Report.pptx"
            )

        os.makedirs(os.path.dirname(output_path), exist_ok=True)

        prs = Presentation()
        # 16:9 Widescreen dimensions: 13.33 x 7.5 inches
        prs.slide_width = Inches(13.333)
        prs.slide_height = Inches(7.5)
        blank_layout = prs.slide_layouts[6] # completely blank slide

        # ==========================================
        # 1. COVER SLIDE
        # ==========================================
        cover = prs.slides.add_slide(blank_layout)

        # Top blue banner shape
        banner = cover.shapes.add_shape(
            MSO_SHAPE.RECTANGLE, Inches(0), Inches(0), Inches(13.333), Inches(0.4)
        )
        banner.fill.solid()
        banner.fill.fore_color.rgb = self.blue
        banner.line.color.rgb = self.blue

        # Title text box
        tb = cover.shapes.add_textbox(Inches(1.0), Inches(1.8), Inches(11.0), Inches(4.0))
        tf = tb.text_frame
        tf.word_wrap = True

        p1 = tf.paragraphs[0]
        p1.text = company.upper()
        p1.font.size = Pt(36)
        p1.font.bold = True
        p1.font.color.rgb = self.dark

        p2 = tf.add_paragraph()
        p2.text = "Placement Preparation Guide"
        p2.font.size = Pt(22)
        p2.font.bold = True
        p2.font.color.rgb = self.blue
        p2.space_before = Pt(12)

        p3 = tf.add_paragraph()
        p3.text = "Generated by Autonomous AI Placement Research Agent"
        p3.font.size = Pt(13)
        p3.font.color.rgb = self.gray
        p3.space_before = Pt(36)

        # ==========================================
        # 2. AGENDA SLIDE
        # ==========================================
        if slides:
            agenda = prs.slides.add_slide(blank_layout)
            banner = agenda.shapes.add_shape(
                MSO_SHAPE.RECTANGLE, Inches(0), Inches(0), Inches(13.333), Inches(0.4)
            )
            banner.fill.solid()
            banner.fill.fore_color.rgb = self.blue
            banner.line.color.rgb = self.blue

            tb = agenda.shapes.add_textbox(Inches(1.0), Inches(0.8), Inches(11.0), Inches(0.8))
            p = tb.text_frame.paragraphs[0]
            p.text = "Agenda & Overview"
            p.font.size = Pt(26)
            p.font.bold = True
            p.font.color.rgb = self.dark

            tb_list = agenda.shapes.add_textbox(Inches(1.0), Inches(1.8), Inches(11.0), Inches(4.8))
            tf_list = tb_list.text_frame
            tf_list.word_wrap = True

            for idx, s in enumerate(slides[:10]):
                p_item = tf_list.paragraphs[0] if idx == 0 else tf_list.add_paragraph()
                title_str = s.get("title", f"Topic {idx+1}") if isinstance(s, dict) else str(s)
                p_item.text = f"{idx + 1}.  {title_str}"
                p_item.font.size = Pt(15)
                p_item.font.color.rgb = self.dark
                p_item.space_before = Pt(6)

        # ==========================================
        # 3. CONTENT SLIDES
        # ==========================================
        for idx, slide_data in enumerate(slides):
            if not isinstance(slide_data, dict):
                continue

            title = slide_data.get("title", f"Slide {idx + 1}")
            content_items = slide_data.get("content", [])

            slide = prs.slides.add_slide(blank_layout)

            # Top blue banner
            banner = slide.shapes.add_shape(
                MSO_SHAPE.RECTANGLE, Inches(0), Inches(0), Inches(13.333), Inches(0.4)
            )
            banner.fill.solid()
            banner.fill.fore_color.rgb = self.blue
            banner.line.color.rgb = self.blue

            # Title
            tb_title = slide.shapes.add_textbox(Inches(0.8), Inches(0.6), Inches(11.5), Inches(0.7))
            p_title = tb_title.text_frame.paragraphs[0]
            p_title.text = title
            p_title.font.size = Pt(24)
            p_title.font.bold = True
            p_title.font.color.rgb = self.dark

            # Check for downloaded image
            image_candidates = [
                os.path.join("app", "output", "images", f"slide_{idx + 1}.jpg"),
                os.path.join("app", "output", "images", f"slide_{idx + 1}.png"),
                os.path.join("app", "output", "images", f"slide_{idx + 1}.jpeg")
            ]
            valid_image_path = None
            for cand in image_candidates:
                if os.path.exists(cand) and os.path.getsize(cand) > 1000:
                    valid_image_path = cand
                    break

            if valid_image_path:
                # Text on Left (width 6.5"), Image on Right (width 4.8")
                tb_content = slide.shapes.add_textbox(Inches(0.8), Inches(1.5), Inches(6.5), Inches(5.0))
                try:
                    slide.shapes.add_picture(
                        valid_image_path, Inches(7.7), Inches(1.5), width=Inches(4.8)
                    )
                except Exception as img_err:
                    print(f"Warning: Could not add image {valid_image_path}: {img_err}")
            else:
                # Full width text (width 11.5")
                tb_content = slide.shapes.add_textbox(Inches(0.8), Inches(1.5), Inches(11.5), Inches(5.0))

            tf_content = tb_content.text_frame
            tf_content.word_wrap = True

            for b_idx, item in enumerate(content_items):
                p_bullet = tf_content.paragraphs[0] if b_idx == 0 else tf_content.add_paragraph()
                p_bullet.text = f"•  {item}"
                p_bullet.font.size = Pt(14)
                p_bullet.font.color.rgb = self.dark
                p_bullet.space_before = Pt(8)

            # Footer
            tb_footer = slide.shapes.add_textbox(Inches(0.8), Inches(6.9), Inches(5.0), Inches(0.4))
            p_f1 = tb_footer.text_frame.paragraphs[0]
            p_f1.text = f"{company} Placement Guide"
            p_f1.font.size = Pt(10)
            p_f1.font.color.rgb = self.gray

            tb_fnum = slide.shapes.add_textbox(Inches(10.0), Inches(6.9), Inches(2.5), Inches(0.4))
            p_f2 = tb_fnum.text_frame.paragraphs[0]
            p_f2.text = f"Slide {idx + 1}"
            p_f2.alignment = PP_ALIGN.RIGHT
            p_f2.font.size = Pt(10)
            p_f2.font.color.rgb = self.gray

        # ==========================================
        # 4. THANK YOU SLIDE
        # ==========================================
        thank_you = prs.slides.add_slide(blank_layout)
        tb_ty = thank_you.shapes.add_textbox(Inches(2.0), Inches(2.5), Inches(9.333), Inches(2.5))
        tf_ty = tb_ty.text_frame
        tf_ty.word_wrap = True

        p_ty1 = tf_ty.paragraphs[0]
        p_ty1.text = "Thank You!"
        p_ty1.alignment = PP_ALIGN.CENTER
        p_ty1.font.size = Pt(36)
        p_ty1.font.bold = True
        p_ty1.font.color.rgb = self.blue

        p_ty2 = tf_ty.add_paragraph()
        p_ty2.text = "Best Wishes For Your Placement Preparation"
        p_ty2.alignment = PP_ALIGN.CENTER
        p_ty2.font.size = Pt(18)
        p_ty2.font.color.rgb = self.dark
        p_ty2.space_before = Pt(12)

        prs.save(output_path)
        print(f"Presentation generated successfully: {output_path}")
        return output_path
