const pptxgen = require("pptxgenjs");
const fs = require("fs");
const path = require("path");

async function generatePPT() {

    const company = process.argv[2];

    if (!company) {

        console.log(
            "Usage: node generate.js Adobe"
        );

        return;
    }

    const slidesPath = path.join(
        "..",
        "app",
        "output",
        "slides",
        `${company}.json`
    );

    if (!fs.existsSync(slidesPath)) {

        console.log(
            "Slides JSON not found!"
        );

        return;
    }

    const slides = JSON.parse(
        fs.readFileSync(
            slidesPath,
            "utf8"
        )
    );

    const pptx = new pptxgen();

    pptx.layout = "LAYOUT_WIDE";

    pptx.author =
        "AI Placement Agent";

    pptx.company =
        "AI Placement Agent";

    pptx.subject =
        `${company} Placement Guide`;

    pptx.title =
        `${company} Placement Preparation`;

    pptx.lang = "en-US";

    // =====================================
    // COVER SLIDE
    // =====================================

    const cover = pptx.addSlide();

    cover.background = {
        color: "F8FAFC"
    };

    cover.addShape(
        pptx.ShapeType.rect,
        {
            x: 0,
            y: 0,
            w: 13.33,
            h: 0.35,
            fill: {
                color: "2563EB"
            },
            line: {
                color: "2563EB"
            }
        }
    );

    cover.addText(
        company.toUpperCase(),
        {
            x: 0.8,
            y: 1.3,
            w: 10,
            h: 0.8,
            fontSize: 30,
            bold: true,
            color: "111827",
            fontFace: "Segoe UI"
        }
    );

    cover.addText(
        "Placement Preparation Guide",
        {
            x: 0.8,
            y: 2.1,
            w: 8,
            h: 0.5,
            fontSize: 20,
            color: "2563EB",
            fontFace: "Segoe UI"
        }
    );

    cover.addText(
        "Generated by AI Placement Research Agent",
        {
            x: 0.8,
            y: 5.2,
            w: 8,
            h: 0.3,
            fontSize: 12,
            color: "6B7280"
        }
    );
    // =====================================
// AGENDA SLIDE
// =====================================

const agenda = pptx.addSlide();

agenda.background = {
    color: "FFFFFF"
};

agenda.addText(
    "Agenda",
    {
        x: 0.6,
        y: 0.5,
        w: 4,
        h: 0.5,
        fontSize: 28,
        bold: true,
        color: "111827"
    }
);

const agendaItems = slides
    .map(
        (slide, index) =>
            `${index + 1}. ${slide.title}`
    )
    .join("\n");

agenda.addText(
    agendaItems,
    {
        x: 0.8,
        y: 1.3,
        w: 8,
        h: 5,
        fontSize: 20,
        color: "374151",
        breakLine: true
    }
);

    // =====================================
    // CONTENT SLIDES
    // =====================================

    slides.forEach((slideData, index) => {

        const slide =
            pptx.addSlide();

        slide.background = {
            color: "FFFFFF"
        };

        // Header Bar

        slide.addShape(
            pptx.ShapeType.rect,
            {
                x: 0,
                y: 0,
                w: 13.33,
                h: 0.45,
                fill: {
                    color: "2563EB"
                },
                line: {
                    color: "2563EB"
                }
            }
        );

        slide.addText(
            slideData.title,
            {
                x: 0.5,
                y: 0.7,
                w: 11,
                h: 0.5,
                fontSize: 28,
                bold: true,
                color: "111827",
                fontFace: "Segoe UI"
            }
        );

        const normalContent = [];
const examples = [];

slideData.content.forEach(item => {

    if (
        item.toLowerCase().includes("example")
    ) {
        examples.push(item);
    }
    else {
        normalContent.push(
            `• ${item}`
        );
    }

});

const bullets =
    normalContent.join("\n");

const exampleText =
    examples.join("\n");

        const imagePath =
            path.join(
                "..",
                "app",
                "output",
                "images",
                `slide_${index + 1}.jpg`
            );

        if (
            fs.existsSync(
                imagePath
            )
        ) {

            slide.addText(
                bullets,
                {
                    x: 0.5,
                    y: 1.4,
                    w: 6,
                    h: 4.5,
                    fontSize: 20,
                    color: "111827",
                    fontFace: "Segoe UI",
                    breakLine: true,
                    margin: 0.05
                }
            );

            slide.addImage(
                {
                    path: imagePath,
                    x: 7,
                    y: 1.3,
                    w: 5.3,
                    h: 3.8
                }
            );

        } else {

            slide.addText(
                bullets,
                {
                    x: 0.7,
                    y: 1.4,
                    w: 11,
                    h: 4.5,
                    fontSize: 20,
                    color: "111827",
                    fontFace: "Segoe UI",
                    breakLine: true,
                    margin: 0.05
                }
            );
        }

        // Footer

        slide.addShape(
            pptx.ShapeType.line,
            {
                x: 0.3,
                y: 6.8,
                w: 12.5,
                h: 0,
                line: {
                    color: "D1D5DB",
                    width: 1
                }
            }
        );

        slide.addText(
            company,
            {
                x: 0.4,
                y: 6.9,
                w: 3,
                h: 0.2,
                fontSize: 10,
                color: "9CA3AF"
            }
        );

        slide.addText(
            `Slide ${index + 1}`,
            {
                x: 11.5,
                y: 6.9,
                w: 1,
                h: 0.2,
                fontSize: 10,
                color: "9CA3AF",
                align: "right"
            }
        );

    });

    // =====================================
    // THANK YOU SLIDE
    // =====================================

    const thankYou =
        pptx.addSlide();

    thankYou.background = {
        color: "F8FAFC"
    };

    thankYou.addText(
        "Thank You",
        {
            x: 4,
            y: 2,
            w: 5,
            h: 1,
            fontSize: 30,
            bold: true,
            align: "center",
            color: "2563EB"
        }
    );

    thankYou.addText(
        "Best Wishes For Your Placement Preparation",
        {
            x: 2,
            y: 3.2,
            w: 8,
            h: 0.5,
            fontSize: 18,
            align: "center",
            color: "374151"
        }
    );

    const outputPath = path.join(
        "..",
        "app",
        "output",
        "presentations",
        `${company}_Placement_Report.pptx`
    );

    await pptx.writeFile({
        fileName: outputPath
    });

    console.log(
        `PPT Created: ${outputPath}`
    );
}

generatePPT();